version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: pedro-landing-page
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
      - ./photo.jpg:/usr/share/nginx/html/photo.jpg:ro
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./certbot/conf:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot:ro
    restart: unless-stopped
    networks:
      - pedro-network
    depends_on:
      - certbot

  certbot:
    image: certbot/certbot
    container_name: pedro-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email pedro@landingpedro.duckdns.org --agree-tos --no-eff-email --force-renewal -d landingpedro.duckdns.org
    networks:
      - pedro-network

networks:
  pedro-network:
    driver: bridge
