version: '3.8'

services:
  web:
    build: .
    container_name: pedro-landing-page-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    environment:
      - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d
    restart: unless-stopped
    networks:
      - pedro-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pedro-landing.rule=Host(`pedro-sanches.com`)"
      - "traefik.http.routers.pedro-landing.tls=true"
      - "traefik.http.routers.pedro-landing.tls.certresolver=letsencrypt"

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: pedro-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - pedro-network
    profiles:
      - monitoring

networks:
  pedro-network:
    driver: bridge
