version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: pedro-landing-page
    ports:
      - "8080:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./styles.css:/usr/share/nginx/html/styles.css:ro
      - ./script.js:/usr/share/nginx/html/script.js:ro
      - ./photo.jpg:/usr/share/nginx/html/photo.jpg:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - pedro-network

networks:
  pedro-network:
    driver: bridge
